/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as SignupImport } from "./routes/signup"
import { Route as LoginImport } from "./routes/login"
import { Route as DonationPageImport } from "./routes/DonationPage"
import { Route as CreateFundImport } from "./routes/CreateFund"
import { Route as IndexImport } from "./routes/index"

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const DonationPageRoute = DonationPageImport.update({
  id: "/DonationPage",
  path: "/DonationPage",
  getParentRoute: () => rootRoute,
} as any)

const CreateFundRoute = CreateFundImport.update({
  id: "/CreateFund",
  path: "/CreateFund",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/CreateFund": {
      id: "/CreateFund"
      path: "/CreateFund"
      fullPath: "/CreateFund"
      preLoaderRoute: typeof CreateFundImport
      parentRoute: typeof rootRoute
    }
    "/DonationPage": {
      id: "/DonationPage"
      path: "/DonationPage"
      fullPath: "/DonationPage"
      preLoaderRoute: typeof DonationPageImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/CreateFund": typeof CreateFundRoute
  "/DonationPage": typeof DonationPageRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/CreateFund": typeof CreateFundRoute
  "/DonationPage": typeof DonationPageRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/CreateFund": typeof CreateFundRoute
  "/DonationPage": typeof DonationPageRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/CreateFund" | "/DonationPage" | "/login" | "/signup"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/CreateFund" | "/DonationPage" | "/login" | "/signup"
  id: "__root__" | "/" | "/CreateFund" | "/DonationPage" | "/login" | "/signup"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateFundRoute: typeof CreateFundRoute
  DonationPageRoute: typeof DonationPageRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateFundRoute: CreateFundRoute,
  DonationPageRoute: DonationPageRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/CreateFund",
        "/DonationPage",
        "/login",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/CreateFund": {
      "filePath": "CreateFund.tsx"
    },
    "/DonationPage": {
      "filePath": "DonationPage.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
