/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as SignupImport } from "./routes/signup"
import { Route as LoginImport } from "./routes/login"
import { Route as FundsImport } from "./routes/funds"
import { Route as CreatefundImport } from "./routes/createfund"
import { Route as AccountImport } from "./routes/account"
import { Route as AboutImport } from "./routes/about"
import { Route as IndexImport } from "./routes/index"
import { Route as FundDetailsFundIdImport } from "./routes/fund-details.$fundId"
import { Route as EditfundEditfundIdImport } from "./routes/editfund.$editfundId"
import { Route as AdminAdminLoginImport } from "./routes/admin/adminLogin"
import { Route as AdminAdminDashboardImport } from "./routes/admin/adminDashboard"
import { Route as AdminAdminFundCardImport } from "./routes/admin/AdminFundCard"

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const FundsRoute = FundsImport.update({
  id: "/funds",
  path: "/funds",
  getParentRoute: () => rootRoute,
} as any)

const CreatefundRoute = CreatefundImport.update({
  id: "/createfund",
  path: "/createfund",
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const FundDetailsFundIdRoute = FundDetailsFundIdImport.update({
  id: "/fund-details/$fundId",
  path: "/fund-details/$fundId",
  getParentRoute: () => rootRoute,
} as any)

const EditfundEditfundIdRoute = EditfundEditfundIdImport.update({
  id: "/editfund/$editfundId",
  path: "/editfund/$editfundId",
  getParentRoute: () => rootRoute,
} as any)

const AdminAdminLoginRoute = AdminAdminLoginImport.update({
  id: "/admin/adminLogin",
  path: "/admin/adminLogin",
  getParentRoute: () => rootRoute,
} as any)

const AdminAdminDashboardRoute = AdminAdminDashboardImport.update({
  id: "/admin/adminDashboard",
  path: "/admin/adminDashboard",
  getParentRoute: () => rootRoute,
} as any)

const AdminAdminFundCardRoute = AdminAdminFundCardImport.update({
  id: "/admin/AdminFundCard",
  path: "/admin/AdminFundCard",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    "/account": {
      id: "/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    "/createfund": {
      id: "/createfund"
      path: "/createfund"
      fullPath: "/createfund"
      preLoaderRoute: typeof CreatefundImport
      parentRoute: typeof rootRoute
    }
    "/funds": {
      id: "/funds"
      path: "/funds"
      fullPath: "/funds"
      preLoaderRoute: typeof FundsImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    "/admin/AdminFundCard": {
      id: "/admin/AdminFundCard"
      path: "/admin/AdminFundCard"
      fullPath: "/admin/AdminFundCard"
      preLoaderRoute: typeof AdminAdminFundCardImport
      parentRoute: typeof rootRoute
    }
    "/admin/adminDashboard": {
      id: "/admin/adminDashboard"
      path: "/admin/adminDashboard"
      fullPath: "/admin/adminDashboard"
      preLoaderRoute: typeof AdminAdminDashboardImport
      parentRoute: typeof rootRoute
    }
    "/admin/adminLogin": {
      id: "/admin/adminLogin"
      path: "/admin/adminLogin"
      fullPath: "/admin/adminLogin"
      preLoaderRoute: typeof AdminAdminLoginImport
      parentRoute: typeof rootRoute
    }
    "/editfund/$editfundId": {
      id: "/editfund/$editfundId"
      path: "/editfund/$editfundId"
      fullPath: "/editfund/$editfundId"
      preLoaderRoute: typeof EditfundEditfundIdImport
      parentRoute: typeof rootRoute
    }
    "/fund-details/$fundId": {
      id: "/fund-details/$fundId"
      path: "/fund-details/$fundId"
      fullPath: "/fund-details/$fundId"
      preLoaderRoute: typeof FundDetailsFundIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/account": typeof AccountRoute
  "/createfund": typeof CreatefundRoute
  "/funds": typeof FundsRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
  "/admin/AdminFundCard": typeof AdminAdminFundCardRoute
  "/admin/adminDashboard": typeof AdminAdminDashboardRoute
  "/admin/adminLogin": typeof AdminAdminLoginRoute
  "/editfund/$editfundId": typeof EditfundEditfundIdRoute
  "/fund-details/$fundId": typeof FundDetailsFundIdRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/account": typeof AccountRoute
  "/createfund": typeof CreatefundRoute
  "/funds": typeof FundsRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
  "/admin/AdminFundCard": typeof AdminAdminFundCardRoute
  "/admin/adminDashboard": typeof AdminAdminDashboardRoute
  "/admin/adminLogin": typeof AdminAdminLoginRoute
  "/editfund/$editfundId": typeof EditfundEditfundIdRoute
  "/fund-details/$fundId": typeof FundDetailsFundIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/account": typeof AccountRoute
  "/createfund": typeof CreatefundRoute
  "/funds": typeof FundsRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
  "/admin/AdminFundCard": typeof AdminAdminFundCardRoute
  "/admin/adminDashboard": typeof AdminAdminDashboardRoute
  "/admin/adminLogin": typeof AdminAdminLoginRoute
  "/editfund/$editfundId": typeof EditfundEditfundIdRoute
  "/fund-details/$fundId": typeof FundDetailsFundIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/account"
    | "/createfund"
    | "/funds"
    | "/login"
    | "/signup"
    | "/admin/AdminFundCard"
    | "/admin/adminDashboard"
    | "/admin/adminLogin"
    | "/editfund/$editfundId"
    | "/fund-details/$fundId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/account"
    | "/createfund"
    | "/funds"
    | "/login"
    | "/signup"
    | "/admin/AdminFundCard"
    | "/admin/adminDashboard"
    | "/admin/adminLogin"
    | "/editfund/$editfundId"
    | "/fund-details/$fundId"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/account"
    | "/createfund"
    | "/funds"
    | "/login"
    | "/signup"
    | "/admin/AdminFundCard"
    | "/admin/adminDashboard"
    | "/admin/adminLogin"
    | "/editfund/$editfundId"
    | "/fund-details/$fundId"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CreatefundRoute: typeof CreatefundRoute
  FundsRoute: typeof FundsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminAdminFundCardRoute: typeof AdminAdminFundCardRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  EditfundEditfundIdRoute: typeof EditfundEditfundIdRoute
  FundDetailsFundIdRoute: typeof FundDetailsFundIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CreatefundRoute: CreatefundRoute,
  FundsRoute: FundsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminAdminFundCardRoute: AdminAdminFundCardRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  EditfundEditfundIdRoute: EditfundEditfundIdRoute,
  FundDetailsFundIdRoute: FundDetailsFundIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/account",
        "/createfund",
        "/funds",
        "/login",
        "/signup",
        "/admin/AdminFundCard",
        "/admin/adminDashboard",
        "/admin/adminLogin",
        "/editfund/$editfundId",
        "/fund-details/$fundId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/account": {
      "filePath": "account.tsx"
    },
    "/createfund": {
      "filePath": "createfund.tsx"
    },
    "/funds": {
      "filePath": "funds.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/admin/AdminFundCard": {
      "filePath": "admin/AdminFundCard.tsx"
    },
    "/admin/adminDashboard": {
      "filePath": "admin/adminDashboard.tsx"
    },
    "/admin/adminLogin": {
      "filePath": "admin/adminLogin.tsx"
    },
    "/editfund/$editfundId": {
      "filePath": "editfund.$editfundId.tsx"
    },
    "/fund-details/$fundId": {
      "filePath": "fund-details.$fundId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
